sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t danibrenna/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true danibrenna/docker-react npm run test